services:
  - type: web
    name: realestate-proj
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn realestate.wsgi:application"
    envVars:
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "realestate-proj.onrender.com"
