# Generated by Django 5.2 on 2025-05-07 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_customuser_is_approved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertymedia',
            old_name='Property',
            new_name='property',
        ),
    ]
