# Generated by Django 5.2 on 2025-05-07 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_rename_property_propertymedia_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='city',
            field=models.CharField(default='نواكشوط', max_length=100),
            preserve_default=False,
        ),
    ]
