# Generated by Django 5.2 on 2025-05-11 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_customuser_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='location',
        ),
        migrations.AddField(
            model_name='property',
            name='district',
            field=models.CharField(blank=True, choices=[('تفرغ زينة', 'تفرغ زينة'), ('دار النعيم', 'دار النعيم'), ('لكصر', 'لكصر'), ('الميناء', 'الميناء'), ('السبخة', 'السبخة'), ('تيارت', 'تيارت'), ('الرياض', 'الرياض'), ('عرفات', 'عرفات'), ('توجونين', 'توجونين')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='main_location',
            field=models.CharField(choices=[('نواكشوط', 'نواكشوط'), ('نواذيبو', 'نواذيبو'), ('كيفة', 'كيفة'), ('لعيون', 'لعيون'), ('زويرات', 'زويرات'), ('النعمة', 'النعمة')], default='نواكشوط', max_length=50),
            preserve_default=False,
        ),
    ]
