# Generated by Django 4.2.23 on 2025-06-30 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_property_is_sold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertymedia',
            name='video',
        ),
        migrations.AddField(
            model_name='property',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='property_main_images/', verbose_name='الصورة الرئيسية'),
        ),
        migrations.AddField(
            model_name='property',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='property_videos/', verbose_name='فيديو العقار'),
        ),
    ]
