# Generated by Django 4.2.23 on 2025-06-30 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0010_remove_propertymedia_video_property_main_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertymedia',
            name='image',
            field=models.ImageField(upload_to='property_images/'),
        ),
    ]
