# Generated by Django 4.2.23 on 2025-07-11 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0011_alter_propertymedia_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('fixed', 'مبلغ ثابت'), ('commission', 'عمولة')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='property_main/'),
        ),
        migrations.AlterField(
            model_name='property',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='property_videos/'),
        ),
    ]
