# Generated by Django 4.2.23 on 2025-07-11 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0012_property_payment_method_alter_property_main_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_used', models.CharField(choices=[('bankily', 'بنكيلي'), ('seddad', 'السداد'), ('bimbank', 'بيم بانك'), ('masrefy', 'مصرفي')], max_length=20)),
                ('screenshot', models.ImageField(upload_to='payment_screenshots/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_proof', to='properties.property')),
            ],
        ),
    ]
