# Generated by Django 4.2.23 on 2025-07-12 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0013_paymentproof'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='payment_proof_file',
            field=models.ImageField(blank=True, null=True, upload_to='payement_proof/'),
        ),
        migrations.AlterField(
            model_name='property',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('fixed', 'مبلغ ثابت'), ('commission', 'عمولة')], max_length=20, null=True),
        ),
    ]
