# Generated by Django 4.2.23 on 2025-07-12 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0014_property_payment_proof_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='app_used',
            field=models.CharField(blank=True, choices=[('bankily', 'بنكيلي'), ('seddad', 'السداد'), ('bimbank', 'بيم بانك'), ('masrefy', 'مصرفي')], max_length=20, null=True),
        ),
    ]
