# Generated by Django 4.2.23 on 2025-07-12 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0015_property_app_used'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='app_used',
        ),
        migrations.RemoveField(
            model_name='property',
            name='payment_proof_file',
        ),
        migrations.AlterField(
            model_name='property',
            name='is_sold',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='property',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
