# Generated by Django 4.2.23 on 2025-06-26 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد المراجعة'), ('approved', 'مقبولة'), ('rejected', 'مرفوضة')], default='pending', max_length=10, verbose_name='حالة الطلب'),
        ),
    ]
