# Generated by Django 4.2.23 on 2025-06-26 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_vehicle_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='vehicles/images/', verbose_name='صورة'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='vehicles/videos/', verbose_name='فيديو'),
        ),
    ]
