# Generated by Django 4.2.23 on 2025-07-11 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_vehicle_description_vehiclemedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('fixed', 'مبلغ ثابت'), ('commission', 'عمولة')], max_length=10, null=True, verbose_name='طريقة الدفع'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='payment_proof',
            field=models.ImageField(blank=True, null=True, upload_to='vehicles/payment_proofs/', verbose_name='لقطة إثبات الدفع'),
        ),
    ]
