# Generated by Django 4.2.23 on 2025-07-13 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0005_vehicle_payment_method_vehicle_payment_proof'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='payment_proof',
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('fixed', 'مبلغ ثابت'), ('commission', 'عمولة')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='VehiclePaymentProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_used', models.CharField(choices=[('bankily', 'بنكيلي'), ('seddad', 'السداد'), ('bimbank', 'بيم بانك'), ('masrefy', 'مصرفي')], max_length=20)),
                ('screenshot', models.ImageField(upload_to='vehicles/payment_proofs/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_proof', to='vehicles.vehicle')),
            ],
        ),
    ]
