# Generated by Django 4.2.23 on 2025-07-25 22:20

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0006_remove_vehicle_payment_proof_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclemedia',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='vehiclepaymentproof',
            name='screenshot',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
